source 'https://rubygems.org'

gem 'activerecord', require: 'active_record'
gem 'erubi'
gem 'mysql2'
gem 'mysql2-cs-bind'
gem 'newrelic_rpm'
gem 'pry'
gem 'puma'
gem 'rake'
gem 'require_all'
gem 'sinatra'
gem 'sinatra-activerecord', require: 'sinatra/activerecord'

group :development do
  gem 'sinatra-contrib'
end
